[package]
name = "rust-drm"
description = "Pure Rust implementation of mesa libdrm for Linux"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-drm/rust-drm"
authors = ["rust-drm developers"]
edition = "2018"

[dependencies]
regex = "1.3.1"
